export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCHED_CATEGORIES = 'FETCHED_CATEGORIES';
export const FETCH_JOKE = 'FETCH_JOKE';
export const FETCHED_JOKE = 'FETCHED_JOKE';
export const FETCH_ERROR = 'FETCH_ERROR';
